// Copyright (c) 2021-2026 Littleton Robotics
// http://github.com/Mechanical-Advantage
//
// Use of this source code is governed by a BSD
// license that can be found in the LICENSE file
// at the root directory of this project.

package frc.robot;

import com.ctre.phoenix6.CANBus;
import edu.wpi.first.wpilibj.RobotBase;

/**
 * Runtime configuration, CAN IDs, and the values that get changed during a tuning or competition
 * session.
 *
 * <p><b>This is the one constants file.</b> There is deliberately no separate {@code
 * HardwareConstants} — the 2026 season had both, and the split meant that changing something
 * between matches involved remembering which of two files it lived in. Everything you reach for
 * with a stopwatch running is here.
 *
 * <h2>What goes here</h2>
 *
 * <ul>
 *   <li><b>CAN IDs</b> — every non-swerve device on the robot, in one table
 *   <li><b>Setpoints</b> — the voltages, velocities and positions a mechanism is commanded to
 *   <li><b>Waits</b> — every timeout used by a command
 *   <li><b>Thresholds</b> — alignment tolerances and readiness bands
 *   <li><b>Mode flags</b> — sim/replay selection, tuning mode
 * </ul>
 *
 * <h2>What stays in the subsystem's own constants file</h2>
 *
 * <ul>
 *   <li><b>Gains</b> — kS/kV/kA/kP/kI/kD, and the sim-versus-real split
 *   <li><b>Current limits</b> — they belong with the motor they protect
 *   <li><b>Gear ratios and mechanical geometry</b>
 *   <li><b>Sim model parameters</b> — motor type, moment of inertia
 *   <li><b>Interpolation maps</b> — a distance-to-RPM shooting table is structure, not a knob, and
 *       it would bury everything else in this file
 * </ul>
 *
 * <p>The dividing line: <b>if you would change it in the pit between matches, it belongs here.</b>
 * If it describes how a mechanism is built or characterized, it belongs with that mechanism.
 *
 * <p>Swerve is the exception to all of this — its CAN IDs, gear ratios, gains and current limits
 * are generated by CTRE Tuner X and live in {@code generated/TunerConstants.java}, which must not
 * be hand-edited. See {@code .claude/rules/02-hardware.md}.
 */
public final class Constants {

  private Constants() {}

  // ============================================================================================
  // RUNTIME MODE
  // ============================================================================================

  /** Which mode to use when not on a real robot. Change to {@link Mode#REPLAY} to replay a log. */
  public static final Mode simMode = Mode.SIM;

  /** Resolved mode. Always {@link Mode#REAL} on a roboRIO. */
  public static final Mode currentMode = RobotBase.isReal() ? Mode.REAL : simMode;

  public static enum Mode {
    /** Running on a real robot. */
    REAL,

    /** Running a physics simulator. */
    SIM,

    /** Replaying from a log file. */
    REPLAY
  }

  /**
   * Set true to skip DriverStation/HAL access in unit tests. Read by {@link
   * frc.lib.AllianceFlipUtil#refresh()}.
   */
  public static boolean disableHAL = false;

  /**
   * Enables dashboard-adjustable constants ({@code LoggedTunableNumber} / {@code
   * LoggedTunableBoolean}).
   *
   * <p><b>MUST BE FALSE FOR COMPETITION.</b> With it on, every tunable publishes to NetworkTables
   * and reads back from it, which puts dashboard traffic in the 20 ms loop and leaves the robot one
   * stray edit away from a different gain set. With it off, tunables return their compiled-in
   * defaults and cost nothing.
   *
   * <p>Turning this on is a deliberate act at the start of a tuning session, and turning it off
   * again is part of the pre-competition checklist. Values discovered while it is on live only in
   * NetworkTables — write them into the constants and commit them, or they vanish on reboot.
   */
  public static final boolean tuningMode = false;

  // ============================================================================================
  // CAN IDs
  // ============================================================================================

  /**
   * Every non-swerve CAN device on the robot.
   *
   * <p>Swerve IDs are not here — they are generated into {@code TunerConstants} by Tuner X.
   *
   * <p><b>Never hardcode a CAN ID in an IO implementation.</b> A magic number in a constructor is
   * invisible in review, and the failure mode when it is wrong is that the code silently commands
   * the wrong motor.
   *
   * <pre>
   * // CORRECT
   * new TalonFX(Constants.CanIds.MECHANISM_LEADER, "rio");
   *
   * // WRONG
   * new TalonFX(30, "rio");
   * </pre>
   *
   * <p><b>Comment the bus on every line</b> — {@code // CANivore} or {@code // RIO CAN}. The bus is
   * not visible from the number, and a device on the wrong bus is simply not found at startup.
   *
   * <p>Mirror every entry into {@code docs/hardware-layout.md} as it is assigned. That table is how
   * you answer "what is on ID 14?" while someone is holding a wire.
   */
  public static final class CanIds {

    private CanIds() {}

    /**
     * The roboRIO's onboard CAN bus.
     *
     * <p>Use this rather than the string form: {@code new TalonFX(id, "rio")} is deprecated for
     * removal in Phoenix 6, and constructing a {@code CANBus} per device wastes work at startup.
     *
     * <p>The CANivore bus is {@code TunerConstants.kCANBus} — swerve owns it, and anything else
     * placed there needs a documented reason (see {@code .claude/rules/02-hardware.md}).
     */
    public static final CANBus RIO_BUS = new CANBus("rio");

    // ============================================================================
    // TODO: DELETE THESE THREE once the first real mechanism lands.
    // ============================================================================
    // They exist only so template/src/ resolves and can be copied without editing two files at
    // once. Nothing on the robot uses them. Leaving them in ships fictional hardware IDs to a
    // competition robot, where the next person to add a mechanism may reuse 20 and get a silent
    // conflict. IDs 0-12 belong to swerve (see TunerConstants), so mechanisms start at 20.
    public static final int EXAMPLE_MOTOR = 20; // RIO CAN
    public static final int EXAMPLE_FOLLOWER = 21; // RIO CAN
    public static final int EXAMPLE_ENCODER = 22; // RIO CAN
  }

  // ============================================================================================
  // SETPOINTS
  // ============================================================================================

  /**
   * What mechanisms are commanded to — voltages, velocities, positions.
   *
   * <p>These change constantly during drive practice, which is exactly why they are here rather
   * than scattered across subsystem files. Name them for what they accomplish, not what they are:
   * {@code SCORE_VELOCITY} rather than {@code VELOCITY_1}.
   */
  public static final class Setpoints {

    private Setpoints() {}

    // public static final Voltage INTAKE_VOLTAGE = Volts.of(8.0);
    // public static final AngularVelocity SCORE_VELOCITY = RPM.of(2400);
    // public static final Angle STOW_POSITION = Degrees.of(0.0);
  }

  // ============================================================================================
  // WAITS
  // ============================================================================================

  /**
   * Every timeout used by a command. None inline.
   *
   * <p>{@code .claude/rules/03-commands.md} requires a timeout on every {@code waitUntil} — a robot
   * that hangs mid-sequence scores zero. Keeping the numbers here means the whole timing budget is
   * readable in one place instead of reconstructed from a dozen command files.
   *
   * <p>For the Ready → Align → Act pattern, the second phase gets the <i>remaining</i> budget, not
   * a fresh one:
   *
   * <pre>
   * Commands.waitUntil(mechanism::isReady).withTimeout(Waits.MECHANISM_READY_SECONDS),
   * Commands.waitUntil(isAligned)
   *     .withTimeout(Waits.TOTAL_TIMEOUT_SECONDS - Waits.MECHANISM_READY_SECONDS),
   * act()
   * </pre>
   */
  public static final class Waits {

    private Waits() {}

    // ============================================================================
    // TODO: REPLACE with measured values, and rename for what they actually gate.
    // ============================================================================
    // Referenced by template/src/.../ExampleCommands.java. Unlike the CAN ID placeholders these
    // are harmless to ship — a timeout of 1.0 s is a real, if arbitrary, timeout. They are still
    // guesses, and a sequence budget nobody measured is a sequence that times out at the worst
    // possible moment.

    /** How long to wait for a mechanism to reach its setpoint before giving up. */
    public static final double MECHANISM_READY_SECONDS = 1.0;

    /**
     * Total budget for a ready-then-align-then-act sequence. Must exceed {@link
     * #MECHANISM_READY_SECONDS}, since phase two is given the difference.
     */
    public static final double TOTAL_TIMEOUT_SECONDS = 1.5;
  }

  // ============================================================================================
  // THRESHOLDS
  // ============================================================================================

  /**
   * Tolerances and readiness bands — how close counts as close enough.
   *
   * <p>Tightening one of these makes the robot wait longer for a better shot; loosening it makes it
   * act sooner and less accurately. That trade is a match-strategy decision, so these get adjusted
   * between matches and belong here.
   *
   * <p>Log the boolean each one produces. A tolerance you cannot see resolving in a match log is
   * one you cannot debug afterward.
   */
  public static final class Thresholds {

    private Thresholds() {}

    // public static final double ALIGNMENT_TOLERANCE_DEGREES = 2.0;
    // public static final double VELOCITY_TOLERANCE_RPM = 100.0;
  }
}
